import os
from typing import List

import pytest

from ssBind.posepicker import *
from ssBind.posepicker import SimplePosePicker
from ssBind.tests.generic import *


@pytest.fixture
def conformers_file(path: str) -> str:
    """Path to conformers sdf for assertion

    Args:
        path (str): path to tests directory

    Returns:
        str: Path to conformers
    """
    return os.path.join(path, "data/conformers.sdf")


@pytest.fixture
def scores_file(path: str) -> str:
    """Path to Scores.csv for assertion

    Args:
        path (str): path to tests directory

    Returns:
        str: Path to scores
    """
    return os.path.join(path, "data/Scores.csv")


@pytest.fixture
def models() -> List[str]:
    """Model compounds generated by the test

    Returns:
        List[str]: Filenames (in current directory)
    """
    return [f"model_{i+1}.sdf" for i in range(10)]


def cleanup(files: List[str]) -> None:
    """Clean up

    Args:
        files (List[str]): Files to remove
    """
    for f in files:
        try:
            os.remove(f)
        except OSError:
            pass


def test_PCA_posepicker(
    conformers_file: str,
    scores_file: str,
    models: List[str],
) -> None:
    """Test clustering of conformers and selecting model posees

    Args:
        conformers_file (str): Path to minimized_conformers.sdf
        scores_file (str): Path to Scores.csv
        models (List[str]): sdf files generated by posepicker
    """

    files = models + ["PC1-PC2.svg", "PC1-PC3.svg", "PC2-PC3.svg"]

    cleanup(files)
    picker = PCAPosePicker()
    picker.pick_poses(conformers_file, scores_file)
    for f in files:
        assert os.path.isfile(f)
    for model in models:
        assert os.path.isfile(model)
    cleanup(files)


def test_torsion_posepicker(
    conformers_file: str, scores_file: str, ligand: Mol
) -> None:
    """Test clustering of conformers and selecting model posees

    Args:
        conformers_file (str): Path to minimized_conformers.sdf
        scores_file (str): Path to Scores.csv
    """

    files = [f"model_{i+1}.sdf" for i in range(1)] + [
        "cluster_info.csv",
        "conf_info.csv",
    ]

    cleanup(files)
    picker = TorsionPosePicker(dG_threshold=0.6, ref_ligands=[ligand])
    picker.pick_poses(conformers_file, scores_file)
    for f in files:
        assert os.path.isfile(f)
    cleanup(files)


def test_simple_posepicker(conformers_file: str, scores_file: str, ligand: Mol) -> None:

    files = ["selected_conformers.sdf"]

    cleanup(files)
    picker = SimplePosePicker(
        query_molecule=ligand,
        clusteringMethod="hdbscan",
        selectionStrategy="mixed",
    )
    picker.pick_poses(conformers_file, scores_file)
    for f in files:
        assert os.path.isfile(f)
    cleanup(files)
